name = "notion-fetch"
type = "javascript"
zone_id = ""
account_id = ""
workers_dev = false
compatibility_date = "2022-07-21"

[build]
command = "npm install && npm run build"
[build.upload]
format = "modules"
main = "./worker.mjs"

[durable_objects]
bindings = [{name = "NOTION_PAGE", class_name = "NotionPage"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["NotionPage"]

[[r2_buckets]]
binding = "DATA_BUCKET" # <~ valid JavaScript variable name
bucket_name = "notion-fetch"

[env.staging]
name = "notion-fetch-staging"
workers_dev = true

[env.staging.durable_objects]
bindings = [{name = "NOTION_PAGE", class_name = "NotionPage"}]

[[env.staging.r2_buckets]]
binding = "DATA_BUCKET" # <~ valid JavaScript variable name
bucket_name = "notion-fetch-staging"
